language: php
php:
  - 7.4.3

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

notifications:
  email: false

stages:
  - test
  - deploy
  
before_install:
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - sudo mysql -e 'CREATE DATABASE IF NOT EXISTS homestead;'
  - composer self-update  
  - composer install --prefer-source --no-interaction --dev 
  - rm .env  

jobs:
  include:
    - stage: test
      install:
        - mv .env.test .env
        - php artisan migrate:fresh --force --no-interaction 
        - php artisan db:seed --force --no-interaction
      script:
        - ./vendor/bin/phpunit
    - stage: deploy
      install:
        - mv .env.deploy .env
      script:
        - echo deploying
      deploy:
        provider: heroku
        script:
          - php artisan migrate:fresh --force --no-interaction 
          - sleep 30
          - php artisan db:seed --force --no-interaction
        api_key:
          secure: $HEROKU_PASSWORD
        on: 
          branch: develop
        app: $HEROKU_APP_NAME
