version: '2'

services:
  mariadb:
    image: bitnami/mariadb:10.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=homestead
      - MARIADB_DATABASE=homestead
      - MARIADB_PASSWORD=secret
    ports:
      - 3306:3306
  crabe:
    tty: true
    image: bitnami/laravel:6-debian-9
    container_name: crabe
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=homestead
      - DB_DATABASE=homestead
      - DB_PASSWORD=secret
    depends_on:
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./:/app
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
    depends_on:
      - mariadb
